version: '3'
services:
  hunter:
    build: ./hunter
    restart: always
    env_file:
      - .env
    links:
      - splunk
  web-api:
    build: ./api
    restart: always
    env_file:
      - .env
    links:
      - splunk
    ports:
     - "3000:3000"
    expose:
      - 3000
  splunk:
    hostname: splunk
    image: splunk/splunk:6.5.3-monitor
    expose:
      - 8088
    environment:
      SPLUNK_CMD: 'add user docker -password docker -role admin -auth admin:changeme'
      SPLUNK_START_ARGS: --accept-license
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
