version: '3'
services:
  streamer:
    build: ./streamer
    environment:
      - MONGO=mongodb://mongo:27017/franklin
      - BIT_API_KEY=1b64d15bace644849152c9e42f7091bc
      - BIT_API_SECRET=5d392d3589004bf9988b72f10022c509
    links:
      - mongo
  hunter:
    build: ./hunter
    environment:
      - MONGO=mongodb://mongo:27017/franklin
    links:
      - mongo
  web:
    build: ./web
    links:
      - web-api
    ports:
     - "5000:5000"
  web-api:
    build: ./api
    environment:
      - MONGO=mongodb://mongo:27017/franklin
      - BIT_API_KEY=1b64d15bace644849152c9e42f7091bc
      - BIT_API_SECRET=5d392d3589004bf9988b72f10022c509
    links:
      - mongo
    ports:
     - "3000:3000"
    expose:
      - 3000
  mongo:
    image: mongo
    volumes:
        - ./scripts/imports:/tmp/dumps
    ports:
     - "27017:27017"
    expose:
     - 27017
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    expose:
      - 9200
      - 5044
