version: '3'
services:
  streamer:
    build: ./streamer
    restart: always
    environment:
      - MONGO=mongodb://mongo:27017/franklin
      - BIT_API_KEY=357a911210354305a4d6993401a4e994
      - BIT_API_SECRET=a42dd9a213d443bfb531f29909725a72
      - SPLUNKTOKEN=00000000-0000-0000-0000-000000000000
      - APP_ENV=docker
      - TIMEINTERVAL=10
    links:
      - mongo
      - splunk
      - web-api
  hunter:
    build: ./hunter
    restart: always
    environment:
      - LOOP_SECONDS=3
      - SPLUNKTOKEN=00000000-0000-0000-0000-000000000000
      - APP_ENV=docker
      - COLLECTION_MINUTES=15
    links:
      - mongo
      - splunk
  web-api:
    build: ./api
    restart: always
    environment:
      - MONGO=mongodb://mongo:27017/franklin
      - BIT_API_KEY=1b64d15bace644849152c9e42f7091bc
      - BIT_API_SECRET=5d392d3589004bf9988b72f10022c509
      - SPLUNKTOKEN=00000000-0000-0000-0000-000000000000
      - APP_ENV=docker
    links:
      - mongo
      - splunk
    ports:
     - "3000:3000"
    expose:
      - 3000
  mongo:
    image: mongo
    restart: always
    volumes:
        - ./scripts/imports:/tmp/dumps
    ports:
     - "27017:27017"
    expose:
     - 27017
  splunk:
    hostname: splunk
    image: splunk/splunk:6.5.3-monitor
    expose:
      - 8088
    environment:
      SPLUNK_CMD: 'add user docker -password docker -role admin -auth admin:changeme'
      SPLUNK_START_ARGS: --accept-license
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
volumes:
  opt-splunk-etc:
  opt-splunk-var:
