version: '3'
services:
  streamer:
    build: ./streamer
    links:
      - mongo
  hunter:
    build: ./hunter
    links:
      - mongo
  web:
    build: ./web
    links:
      - web-api
    ports:
     - "5000:5000"
  web-api:
    build: ./api
    links:
      - mongo
    ports:
     - "3000:3000"
    expose:
      - 3000
  mongo:
    image: mongo
    ports:
     - "27017:27017"
    expose:
     - 27017
